/*
 * Copyright © 2025 Victoria Coacci, Daniel Duda, Fattori Filippo
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the “Software”), to deal in the
 * Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the
 * following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package it.unicam.cs.hackhub.security;

import io.jsonwebtoken.*;
import io.jsonwebtoken.security.Keys;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Date;

/**
 * Utility component for generating and validating JSON Web Tokens (JWT).
 *
 * <p>
 * This class provides methods for creating signed JWT tokens and extracting claims
 * from existing tokens. It uses a secret key configured through application properties
 * to ensure token integrity and authenticity.
 * </p>
 *
 * <p>
 * JWT tokens generated by this class include the user's email as subject and role
 * as a custom claim, and are used for stateless authentication within the application.
 * </p>
 */
@Component
public class JwtUtil {

    @Value("${jwt.secret}")
    private String secret;

    @Value("${jwt.expiration}")
    private long expiration;

    private SecretKey key;

    /**
     * Initializes the secret signing key used for JWT generation and validation.
     *
     * <p>
     * This method is automatically invoked after dependency injection to construct
     * the {@link SecretKey} from the configured secret string.
     * </p>
     */
    @PostConstruct
    public void init(){
        key = Keys.hmacShaKeyFor(secret.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generates a signed JWT token containing the specified email and role.
     *
     * <p>
     * The generated token includes the subject (email), role claim, issue date,
     * expiration date, and is signed using the configured secret key.
     * </p>
     *
     * @param email the email of the authenticated user
     * @param role the role assigned to the user
     * @return the generated JWT token
     */
    public String generateToken(String email, String role){

        return Jwts.builder()
                .setSubject(email)
                .claim("role", role)
                .setIssuedAt(new Date())
                .setExpiration(new Date(System.currentTimeMillis()+expiration))
                .signWith(key, SignatureAlgorithm.HS256)
                .compact();
    }

    /**
     * Extracts and returns the claims contained in the specified JWT token.
     *
     * <p>
     * This method validates the token signature and returns the associated claims
     * if the token is valid.
     * </p>
     *
     * @param token the JWT token to parse
     * @return the {@link Claims} contained in the token
     * @throws io.jsonwebtoken.JwtException if the token is invalid or cannot be parsed
     */
    public Claims getClaims(String token){
        return Jwts.parserBuilder().setSigningKey(key).build()
                .parseClaimsJws(token).getBody();
    }
}
