/*
 * Copyright © 2025 Victoria Coacci, Daniel Duda, Fattori Filippo
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the “Software”), to deal in the
 * Software without restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so, subject to the
 * following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package it.unicam.cs.hackhub.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;


/**
 * JPA entity representing a user account within the HackHub system.
 *
 * <p>
 * Each {@code Account} stores personal information, authentication credentials,
 * and an associated {@link Role} that defines authorization privileges.
 * </p>
 *
 * <p>
 * This entity is mapped to the database table {@code accounts}
 * and managed through JPA/Hibernate.
 * </p>
 */
@Entity
@Table(name = "accounts")
@Getter
@Setter
public class Account {

    /**
     * Primary key of the account.
     *
     * <p>
     * Automatically generated by the database using IDENTITY strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_account")
    private Long idAccount;

    /**
     * Account holder's first name.
     */
    @Column(nullable = false, length = 50)
    private String name;

    /**
     * Account holder's surname.
     */
    @Column(length = 50)
    private String surname;

    /**
     * Unique nickname used inside the platform.
     */
    @Column(nullable = false, unique = true, length = 50)
    private String nickname;

    /**
     * Unique email address used for authentication.
     */
    @Column(nullable = false, unique = true, length = 100)
    private String email;

    /**
     * Encrypted password of the account.
     *
     * <p>
     * The password must be stored in hashed form (e.g., BCrypt).
     * </p>
     */
    @Column(nullable = false)
    private String password;

    /**
     * Role assigned to the account.
     *
     * <p>
     * Stored as a String value in the database to preserve
     * enum stability across refactorings.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    /**
     * Indicates whether the account is disabled.
     */
    @Column(nullable = false)
    private boolean disabled;

    /**
     * Protected no-argument constructor required by JPA.
     */
    protected Account() {
    }

    /**
     * Constructs a new {@code Account} with mandatory fields.
     *
     * @param name     the account holder's first name
     * @param surname  the account holder's surname
     * @param email    the account holder's email address
     * @param role     the assigned {@link Role}
     * @param nickname the chosen unique nickname
     * @param password the raw password (must be encrypted before persistence)
     * @throws IllegalArgumentException if any parameter is invalid
     */
    public Account(String name,
                   String surname,
                   String email,
                   Role role,
                   String nickname,
                   String password) {

        setName(name);
        setSurname(surname);
        setEmail(email);
        setRole(role);
        setNickname(nickname);
        setPassword(password);
        this.disabled = false;
    }

    /**
     * Sets the account holder's name.
     *
     * @param name the name to set
     * @throws IllegalArgumentException if name is null or blank
     */
    public void setName(String name) {
        if (name == null || name.isBlank())
            throw new IllegalArgumentException("Name cannot be blank");
        this.name = name;
    }

    /**
     * Sets the account holder's surname.
     *
     * @param surname the surname to set
     * @throws IllegalArgumentException if surname is null or blank
     */
    public void setSurname(String surname) {
        if (surname == null || surname.isBlank())
            throw new IllegalArgumentException("Surname cannot be blank");
        this.surname = surname;
    }

    /**
     * Sets the account holder's email.
     *
     * @param email the email to set
     * @throws IllegalArgumentException if email is null or blank
     */
    public void setEmail(String email) {
        if (email == null || email.isBlank())
            throw new IllegalArgumentException("Email cannot be blank");
        this.email = email;
    }

    /**
     * Assigns a role to the account.
     *
     * @param role the role to assign
     * @throws IllegalArgumentException if role is null
     */
    private void setRole(Role role) {
        if (role == null)
            throw new IllegalArgumentException("Role cannot be null");
        this.role = role;
    }

    /**
     * Sets the account nickname.
     *
     * @param nickname the nickname to set
     * @throws IllegalArgumentException if nickname is null or blank
     */
    public void setNickname(String nickname) {
        if (nickname == null || nickname.isBlank())
            throw new IllegalArgumentException("Nickname cannot be blank");
        this.nickname = nickname;
    }

    /**
     * Sets the password for the account.
     *
     * <p>
     * This method allows password initialization only once.
     * </p>
     *
     * @param password the password to set
     * @throws IllegalArgumentException if password is null, blank
     *
     */
    public void setPassword(String password) {
        if (password == null || password.isBlank())
            throw new IllegalArgumentException("Password cannot be blank");
        /*if (this.password != null)
            throw new IllegalArgumentException("Password already set");*/
        this.password = password;
    }

    /**
     * Changes the current password.
     *
     * <p>
     * Validates that both passwords are non-null and non-empty.
     * This method replaces the stored password without performing
     * credential verification; validation logic is expected
     * to be handled at a higher application layer.
     * </p>
     *
     * @param oldPassword the current password (used for validation at service level)
     * @param newPassword the new password to assign
     * @throws IllegalArgumentException if either password is null or blank
     */
    /*public void changePassword(String oldPassword, String newPassword) {

        if (oldPassword == null || newPassword == null)
            throw new IllegalArgumentException("Password cannot be null");

        if (newPassword.isBlank() || oldPassword.isBlank())
            throw new IllegalArgumentException("New password cannot be blank");

        this.password = newPassword;
    }*/
}
