spring.application.name=hackhub
app.cors.allowed-origins=http://localhost:4200
app.security.password-pepper=H7!kL9z$2pWqR5vT8*bN3mQ1xZ0yV4uC6@jF2sE9iG7!
# JWT
jwt.secret=9f8a2c7e1b4d6f0a5e3c9d7b2a1f8e4c6b5d9a0e3f7c2b8d1a4e6f5c9b7
jwt.expiration=86400000

# datasource configuration

spring.datasource.url=jdbc:h2:file:./database/hackhubdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update